CREATE TABLE bank_user(
	userID BIGSERIAL PRIMARY KEY NOT NULL ,
	firstName VARCHAR(32) NOT NULL,
	lastName VARCHAR (32) NOT NULL,
	email VARCHAR (255) NOT NULL,
	password VARCHAR (32) NOT NULL,
	unique(email)

);
-- Table: public.BankUsers

-- DROP TABLE IF EXISTS public."BankUsers";

CREATE TABLE IF NOT EXISTS public."BankUsers"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FirstName" text COLLATE pg_catalog."default" NOT NULL,
    "LastName" text COLLATE pg_catalog."default" NOT NULL,
    "Email" text COLLATE pg_catalog."default" NOT NULL,
    "Password" integer NOT NULL,
    amount integer NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BankUsers" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."BankUsers"
    OWNER to postgres;